### ISSUE TITLE
Wymagane pola przy dodawaniu nowej encji

### ISSUE THREAD

**Issue by markotny** [Wydatex/wydatex_backend#19]
W tej chwili używany jest ten sam model do wszystkiego i nie do końca rozumiem które pola są faktycznie wymagane? W tej chwili pytam w kontekście modelu Budget ale zakładam że ta sama zagwozdka będzie przy wszystkich modelach. Na pewno pole `id` nie jest wymagane bo widze że przychodzi w odpowiedzi wygenerowane. Listy `incomes`, `expenses` zakładam ze też niepotrzebne ale co z `isActive`? Ja mam przesyłać domyślnie `true` czy to jest na bazie czy jak? 
IMO dobrze by było zrobić po prostu osobne modele do Requestów żeby nie było takiego syfu i zgadywania

**Comment by markotny** [comment]
Raczej bez tego się nie obejdzie bo nie widze sposobu w jaki mam np dodać Budżet z kategoriami. Przy dodawaniu normlanie przesłałbym liste id-ków kategorii a jak mam posłużyć sie modelem Budget to on ma w środku `List<BudgetCategory> BudgetCategories` i to nie jest używalne bo obiekt `BudgetCategory` ma w środku `BudgetId`, a ten id to ja dostane w odpowiedzi po dodaniu dopiero. Inna sprawa że (na 90% pewny jestem) jak spróbujecie przez entityFramework wykonać taki Add z listą `BudgetCategories` to on spróbuje utworzyć wpisy w tej tabeli bo to jest Navigation property i wyrzuci błąd że są zduplikowane klucze

**Comment by markotny** [comment]
![image](https://user-images.githubusercontent.com/2085756/81100423-cc687a00-8f0c-11ea-86e0-40510a70ff93.png)
żeby nie być gołosłownym - jednym requestem moge sobie całą baze postawić wykorzystując navigation properties xd

![image](https://user-images.githubusercontent.com/2085756/81100678-34b75b80-8f0d-11ea-91a7-ce880f6028a9.png)
I to o czym pisałem - jak podamy id to entity framework analogicznie spróbuje dodać wpis i sie wysypie.

![image](https://user-images.githubusercontent.com/2085756/81101121-f0788b00-8f0d-11ea-8c1a-7bc704bde3b7.png)
Można to ominąć budując zapytanie w ten sposób i w zasadzie dało by rade wszystkie zapytania chyba tak przecisnąć ale no mając na uwadze jakie cuda można zrobić mając takie modele IMO powinniśmy stworzyć dedykowane modele DTO.

**Comment by RegRom** [comment]
Ogólnie to ja się z Tobą zgadzam. W sumie to nie wiem czemu nie zrobiliśmy żadnych DTO, bo zawsze robiłem. Chyba stało się tak dlatego, że Bartek zrobił to generyczne API, które opiera się na tej jednej grupie modeli, a reszta opiera się na tych generykach i tak to wyszło. Muszę się skonsultować z Bartkiem jak on to w ogóle widział na początku, ale no ja bym zrobił normalnie te DTO i mógłbym się za to zabrać jutro.

**Comment by RegRom** [comment]
Masz też rację z tworzeniem budżetu, powinno to działać tak, że dajesz listę id kategorii z budżetem i wtedy na backendzie tworzone są BudgetCategories powiązane z tymi kategoriami i budżetem.

**Comment by markotny** [comment]
> 
> 
> @markotny czy Issue można zamknąć? DTO i ViewModele są zrobione i weszły w #23

Tak
