### ISSUE TITLE
Niepoprawna odpowiedź Created

### ISSUE THREAD

**Issue by markotny** [Wydatex/wydatex_backend#32]
![image](https://user-images.githubusercontent.com/2085756/81846719-d44e9c80-9552-11ea-848e-75e66ba08770.png)
Spoko że chcemy zwracać odpowiednie statusy HTTP zgodnie z RESTem, jestem jak najbardziej za ale skoro już to robimy to róbmy to dobrze, a nie oszukujemy nullami xd
Status 201, jak widać po parametrach funkcji, musi zwracać adres dodanego elementu, tak jest w specyfikacji -> https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html
Adres ten jest w headerze location -> https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location

dotnet i tak już nam bardzo ułatwia sprawe gotowymi metodami to z nich skorzystajmy:
![image](https://user-images.githubusercontent.com/2085756/81847221-9736da00-9553-11ea-991a-d617f117eeda.png)

**Comment by RegRom** [comment]
A to trzeba gonić @bartoszprokopowicz, bo ja chciałem zwracać route, ale on stwierdził, że on nie da route tylko null xD Ale luźno, zrobię to jutro tak jak należy.

**Comment by RegRom** [comment]
Poprawka weszła w #28 więc zamykam
